# Generated by Django 4.1.13 on 2023-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_id", models.CharField(max_length=255)),
                ("recipe_id", models.CharField(max_length=100, unique=True)),
                ("dishName", models.CharField(max_length=255)),
                ("ingredients", models.JSONField(default=list)),
                ("steps", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="userId",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
